apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: result-trigger-authentication
  namespace: result
spec:
  secretTargetRef:
    - parameter: host
      name: result-env
      key: RABBITMQ_HOST
    - parameter: username
      name: result-env
      key: RABBITMQ_USER
    - parameter: password
      name: result-env
      key: RABBITMQ_PASSWORD